# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2  # CircleCI version
jobs:  # Build-Test-Deplot (BTD) process
    build:  # a build job
        docker:  # run with Docker
            - image: circleci/python:3.7  # Python container
        
        parallelism: 4  # speed up with max value in free account

        # CircleCI working directory to run the steps
        working_directory: ~/project
        
        # Perform the job
        steps:
            - checkout  # Check out the source code into working directory
            
            - restore_cache:  # use saved dependency cache if no change in requirements.txt
                keys:
                    - v1-dependencies-{{ checksum "requirements.txt" }}
                    # fallback to using the latest cache if checksum fails
                    - v1-dependencies-
            
            - run:  # Create Miniconda (faster than Anaconda for CI) and install dependencies
                name: Install dependencies
                command: |
                    cd scripts
                    bash 1_setup_system.sh
                    bash 2_install_miniconda.sh
                    . $HOME/miniconda3/etc/profile.d/conda.sh
                    conda activate lagom
                    bash 3_setup_envs.sh 
                    cd ..
                    pip install -q mock
                    conda install -q -y pytorch-nightly-cpu -c pytorch
                    # Install current project
                    pip install -e .
            
            - save_cache:  # Save dependency cache
                key: v1-dependencies-{{ checksum "requirements.txt" }}
                paths:
                    - ./cache
            
            - run:  # Run tests !
                name: Run tests
                command: |
                    # Activate conda environment
                    . $HOME/miniconda3/etc/profile.d/conda.sh
                    conda activate lagom
                    # Run test files
                    pytest test/ -v
                    # flake8 check for code style and quality
                    flake8 lagom/
                    # make doc
                    cd docs
                    make html
            
            - store_artifacts:  # Save artifacts
                path: artifacts/
                destination: build

            - store_test_results:  # Upload test results
                path: test-reports/
                destination: test-reports

